package com.run.guice;

import com.google.inject.AbstractModule;
import com.google.inject.Inject;
import com.google.inject.Key;
import com.google.inject.name.Named;
import io.vertx.core.Vertx;
import io.vertx.pgclient.PgBuilder;
import io.vertx.pgclient.PgConnectOptions;
import io.vertx.sqlclient.Pool;
import io.vertx.sqlclient.PoolOptions;

/**
 * {@code @Author:张少虎}
 * {@code @Date: 2025/3/12  22:14}
 * {@code @Version 1.0}
 * {@code @注释: }
 */
public class SqlPoolModule extends AbstractModule {

    @Inject
    @Named("run.server.datasource.url")
    private String url;

    @Inject
    @Named("run.server.datasource.host")
    private String host;

    @Inject
    @Named("run.server.datasource.port")
    private Integer port;
    @Inject
    @Named("run.server.datasource.database")
    private String database;
    @Inject
    @Named("run.server.datasource.username")
    private String username;
    @Inject
    @Named("run.server.datasource.password")
    private String password;
    @Inject
    private Vertx vertx;

    @Override
    protected void configure() {
        PgConnectOptions connectOptions = new PgConnectOptions()
                .setPort(this.port)
                .setHost(this.host)
                .setDatabase(this.database)
                .setUser(this.username)
                .setPassword(this.password);
        PoolOptions poolOptions = new PoolOptions()
                .setMaxSize(30);
        Pool pool = PgBuilder
                .pool()
                .with(poolOptions)
                .connectingTo(connectOptions)
                .using(vertx)

                .build();
        bind(Key.get(Pool.class)).toInstance(pool);
    }

//    @Override
//    protected void configure() {
//        JDBCConnectOptions connectOptions = new JDBCConnectOptions()
//                .setJdbcUrl(this.url)
//                .setUser(this.username)
//                .setPassword(this.password)
//                .setAutoGeneratedKeys(false);
//        PoolOptions poolOptions = new PoolOptions()
//                .setMaxSize(30);
//        Pool pool = JDBCPool.pool(vertx, connectOptions, poolOptions);
//        bind(Key.get(Pool.class)).toInstance(pool);
//    }
}