package com.run.dagger.module;

import com.run.common.config.AppConfig;
import com.run.common.config.DataBase;

import dagger.Module;
import dagger.Provides;
import io.vertx.core.Vertx;
import io.vertx.core.json.JsonObject;
import io.vertx.jdbcclient.JDBCConnectOptions;
import io.vertx.jdbcclient.JDBCPool;
import io.vertx.pgclient.PgBuilder;
import io.vertx.pgclient.PgConnectOptions;
import io.vertx.sqlclient.Pool;
import io.vertx.sqlclient.PoolOptions;
import org.jooq.SQLDialect;

import javax.inject.Inject;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Map;

/**
 * {@code @Author:张少虎}
 * {@code @Date: 2025/3/12  22:14}
 * {@code @Version 1.0}
 * {@code @注释: }
 */

@Module
public class SqlPoolModule {

    private Pool getPoolByPgsql(Vertx vertx, AppConfig appConfig) {
        DataBase database = appConfig.getDatabase();
        PgConnectOptions connectOptions = new PgConnectOptions()
                .setPort(database.getPort())
                .setHost(database.getHost())
                .setDatabase(database.getDatabase())
                .setUser(database.getUsername())
                .setPassword(database.getPassword());
        PoolOptions poolOptions = new PoolOptions()
                .setMaxSize(30);
        return PgBuilder
                .pool()
                .with(poolOptions)
                .connectingTo(connectOptions)
                .using(vertx)
                .build();
    }

    private Pool getPoolByH2(Vertx vertx, AppConfig appConfig) {
        String dataPath = appConfig.getSystem().getDataPath();
        Path path = Paths.get(dataPath + "/database/h2");
        path = path.toAbsolutePath();
        String jdbcUrl = "jdbc:h2:file:" + path + "/runify;DATABASE_TO_UPPER=false";
        JDBCConnectOptions connectOptions = new JDBCConnectOptions()
                .setJdbcUrl(jdbcUrl)
                .setAutoGeneratedKeys(false);
        PoolOptions poolOptions = new PoolOptions()
                .setMaxSize(30);
        return JDBCPool.pool(vertx, connectOptions, poolOptions);
    }

    private Pool getPoolBySqlite(Vertx vertx, AppConfig appConfig) {
        String dataPath = appConfig.getSystem().getDataPath();
        String jdbcUrl = "jdbc:sqlite:" + dataPath + "/database/sqlite/runify.db?journal_mode=WAL&synchronous=NORMAL";
        JDBCConnectOptions connectOptions = new JDBCConnectOptions()
                .setJdbcUrl(jdbcUrl)
                .setAutoGeneratedKeys(false)
                .setExtraConfig(new JsonObject(Map.of("encoderCls", "com.run.common.encoder.SqliteJDBCEncoderImpl")));
        PoolOptions poolOptions = new PoolOptions()
                .setMaxSize(1);
        return JDBCPool.pool(vertx, connectOptions, poolOptions);

    }

    @Inject
    @Provides
    public Pool pool(Vertx vertx, AppConfig appConfig) {
        SQLDialect type = appConfig.getDatabase().getType();
        if (type == SQLDialect.SQLITE) {
            return getPoolBySqlite(vertx, appConfig);
        } else if (type == SQLDialect.H2) {
            return getPoolByH2(vertx, appConfig);
        }
        return getPoolByPgsql(vertx, appConfig);
    }

}